name: 'Setup SAP BTP subaccount'
on: workflow_dispatch

defaults:
  run:
    working-directory: terraform

jobs:
  setupbtp:
    env:
      BTP_USERNAME: ${{ secrets.USERNAME }}
      BTP_PASSWORD: ${{ secrets.PASSWORD }}
      TF_VAR_globalaccount: ${{ vars.TF_VAR_globalaccount }}
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_CF_USER: ${{ secrets.USERNAME }}
      TF_VAR_CF_PW: ${{ secrets.PASSWORD }}
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
    - name: Use variables
      run: |
        echo region: $TF_VAR_CF_region
        echo secret/username: $TF_CF_USER
        echo ${{ secrets.USERNAME }}
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: List directory
      run: |
        ls -la 

    - name: Terraform plan 
      id: plan 
      run: terraform plan --var-file terraform.tfvars

    - name: Terraform apply 
      id: apply 
      run: terraform apply --var-file terraform.tfvars
