name: 'Setup SAP BTP subaccount'
on: workflow_dispatch

env:
    BTP_USERNAME: ${secrets.USERNAME}
    BTP_PASSWORD: ${secrets.PASSWORD}
    TF_CF_globalaccount: ${secrets.TF_VAR_globalaccount}
    TF_CF_region: ${vars.TF_VAR_region}
    TF_CF_USER: ${secrets.USERNAME}
    TF_CF_PW: ${secrets.PASSWORD}

defaults:
  run:
    working-directory: terraform

jobs:
  setupbtp:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
    - name: Use variables
      run: |
        echo region: $TF_CF_region
        echo secret/username: $TF_CF_USER
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: List directory
      run: |
        ls -la

    - name: Terraform plan 
      id: plan 
      run: terraform plan --var-file terraform.tfvars

    - name: Terraform apply 
      id: apply 
      run: terraform apply --var-file terraform.tfvars
