name: 'Setup SAP BTP subaccount'
on: workflow_dispatch

jobs:
  setupbtp:
    outputs:
      apiendpoint: ${{ steps.tfvars.outputs.apiendpoint }}
      cforg: ${{ steps.tfvars.outputs.cforg }}
      space: ${{ steps.tfvars.outputs.space }}
    defaults:
      run:
        working-directory: ./terraform
    env:
      BTP_USERNAME: ${{ secrets.USERNAME }}
      BTP_PASSWORD: ${{ secrets.PASSWORD }}
      TF_VAR_globalaccount: ${{ vars.TF_VAR_globalaccount }}
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_CF_USER: ${{ secrets.USERNAME }}
      TF_VAR_CF_PW: ${{ secrets.PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: List directory
        run: |
          ls -la
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan --var-file terraform.tfvars -out tfplan.out

      - name: Terraform apply
        id: apply
        run: terraform apply tfplan.out

      - name: provide variables for other jobs
        id: tfvars
        run: |
          apiendpoint=$(terraform output -raw api_endpoint)
          space=$(terraform output -raw space_name)
          cforg=$(terraform output -raw cf_org_id)
          echo "apiendpoint=$apiendpoint" >> $GITHUB_OUTPUT
          echo "cforg=$cforg" >> $GITHUB_OUTPUT
          echo "space=$space" >> $GITHUB_OUTPUT

  buildmta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install MTA Build Tool
        run: npm install -g mbt
      - name:
        run: npm install
      - name: npm run CDS build
        run: |
          npx -p @sap/cds-dk cds build --production

      - name: trigger mbt
        run: |
          mbt build -e live.mtaext --mtar BPVerification.mtar

      - uses: actions/upload-artifact@master
        with:
          name: BPVerification.mtar
          path: mta_archives/BPVerification.mtar

  deploy_mta:
    runs-on: ubuntu-latest
    needs: [setupbtp, buildmta]
    steps:
      - name: Download artefact
        uses: actions/download-artifact@master
        with:
          name: BPVerification.mtar

      - name: Deploy to Cloud Foundry
        uses: guerric-p/cf-cli-action@master
        with:
          cf_api: ${{ needs.setupbtp.outputs.apiendpoint }}
          cf_username: ${{ secrets.USERNAME }}
          cf_password: ${{ secrets.PASSWORD }}
          cf_org: ${{ needs.setupbtp.outputs.cforg }}
          cf_space: ${{ needs.setupbtp.outputs.space }}
          command: deploy BPVerification.mtar -f
